name: borsellino
description: A multi chain Cosmos Hub wallet.

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"


# Project dependencies
dependencies:
  flutter:
    sdk: flutter

  hex: ^0.1.2
  http: ^0.12.0
  basic_utils: ^1.2.0
  meta: ^1.1.7
  shared_preferences: ^0.5.3+4

  # Crypto
  bip39: ^1.0.3
  sacco: ^0.0.7

  # Dependency injection
  dependencies: ^0.1.5
  dependencies_flutter: ^0.1.6

  # BLoC pattern
  bloc: ^0.14.0
  equatable: ^0.5.0
  flutter_bloc: ^0.19.0

  # Storage
  flutter_secure_storage: ^3.2.1+1
  path_provider: ^1.2.0
  sembast: ^2.0.1

  # String formatting
  sprintf: ^4.0.2

  # UI
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0

  # Sharing data
  share: ^0.6.2

  # URL opening
  url_launcher: ^5.1.0


#############
# Development only dependencies
dev_dependencies:
  pedantic: ^1.0.0

  flutter_test:
    sdk: flutter

#############
# Generic flutter setup
flutter:
  uses-material-design: true
