name: borsellino
description: A multi chain Cosmos Hub wallet.

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"


# Project dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # Dependency injection
  dependencies_flutter: ^0.1.6

  # BLoC pattern
  equatable: ^0.3.0
  flutter_bloc: ^0.19.0

  hex: ^0.1.2
  http: ^0.12.0
  basic_utils: ^1.2.0

  # Crypto utils
  bip39: ^1.0.3
  bitcoin_flutter: ^1.0.7
  pointycastle: ^1.0.1
  bip_bech32: ^0.1.3

  # Serialization
  json_annotation: ^2.4.0
  protobuf: ^0.13.12

  # Secure storage
  flutter_secure_storage: ^3.2.1+1

  # noSQLite database
  path_provider: ^1.2.0
  sembast: ^2.0.1

  # String formatting
  sprintf: ^4.0.2

  # UI
  flutter_staggered_grid_view: ^0.3.0

  # Sharing data
  share: ^0.6.2

  # URL opening
  url_launcher: ^5.1.0


#############
# Development only dependencies
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  pedantic: ^1.0.0

  flutter_test:
    sdk: flutter

#############
# Generic flutter setup
flutter:
  uses-material-design: true
