name: borsellino
description: The official Commercio.network wallet.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"


# Project dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # Dependency injection
  dependencies_flutter: ^0.1.6

  # BLoC pattern
  equatable: ^0.3.0
  flutter_bloc: ^0.19.0

  http: ^0.12.0
  basic_utils: ^1.2.0

  # Crypto utils
  bip39: ^1.0.3
  bitcoin_flutter: ^1.0.7
  pointycastle: ^1.0.1
  bip_bech32: ^0.1.3
  protobuf: ^0.13.12
  json_annotation: ^2.4.0

  # Secure storage
  flutter_secure_storage: ^3.2.1+1

  # Shared preferences
  shared_preferences: ^0.5.3+4

  # String formatting
  sprintf: ^4.0.2

  # UI
  auto_size_text: ^2.0.2+1

  # Sharing data
  share: ^0.6.2


#############
# Development only dependencies
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  pedantic: ^1.0.0

  flutter_test:
    sdk: flutter

#############
# Generic flutter setup
flutter:
  uses-material-design: true
